# Generated by Django 5.2.4 on 2025-07-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_remove_user_profile_image_url_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='stylist',
            name='image_url',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
        migrations.AddField(
            model_name='stylist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stylist_images/'),
        ),
    ]
