# Generated by Django 5.2.4 on 2025-07-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_appointment_discount_appointment_final_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspiredWork',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='inspired_work/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
