# Generated by Django 5.2.4 on 2025-07-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_remove_service_image_url_remove_stylist_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='image',
            field=models.ImageField(default=1, upload_to='portfolio_images/'),
            preserve_default=False,
        ),
    ]
