# Generated by Django 5.2.4 on 2025-07-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_remove_portfolioimage_image_url_portfolioimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(to='salon.service'),
        ),
    ]
