# Generated by Django 5.2.4 on 2025-07-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_remove_appointment_service_appointment_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='stylist',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='stylists', to='salon.category'),
        ),
    ]
